theme = "gruvbox"

[editor.file-picker]
hidden = false

[editor]
color-modes = true
soft-wrap.enable = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
select = "underline"
