[[language]]
name = "rust"

[[language]]
name = "markdown"
language-servers = ["/usr/bin/ltex-ls"]
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []

[language-server.golangci-lint-langserver]
command = "golangci-lint-langserver"
config = {command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]}

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-langserver"]
